import "../style/home/global.css";
import Navi from "../components/home/navigation";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {<Navi></Navi>}
        {children}
      </body>
    </html>
  );
}
